package com.mytrip.demo.application.persistance.trip;

import com.mytrip.demo.application.persistance.trip.event.TripEventJpa;
import com.mytrip.demo.application.persistance.user.UserJpa;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.RequiredArgsConstructor;

import javax.persistence.*;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

@RequiredArgsConstructor
@Data
@Builder
@AllArgsConstructor
@Entity(name = "trip")
public class TripJpa {

    @Id
    private Long id;

//    add this column as autogenerated
    private UUID trip_uuid = UUID.randomUUID();
    private String creator;
    private String title;
    private LocalDate from;
    private LocalDate to;

    @ManyToMany
    private List<UserJpa> participants;

    @OneToMany
    private List<TripEventJpa> tripEvents;

    public void addParticipants(UserJpa user) {
        participants.add(user);
    }
}
