@startuml
skinparam actorStyle awesome

actor "User/Participant" as User

(new trip element created) as new_trip_element

rectangle "create new trip element" as cnte {

    "wish to create new trip element" as (wish)

    "check weather" as (check_weather)
    "check price" as (check_price)
    "check dates" as (check_dates)

    User -d-|> wish

    wish -d-> transfer : create transfer
    wish -d-> accommodation: create accommodation
    wish -d-> regional_trip : create regional trip

    rectangle transfer {
        "find transfer" as (transfer_find)

        transfer_find .d.> check_price
    }

    rectangle accommodation {
        "find accommodation" as (accommodation_find)

        accommodation_find .d.> check_weather
    }

    rectangle "regional trip" as regional_trip {
        "find transfer" as (regional_find)

        regional_find .d.> check_weather
    }

    check_price .u.> wish : too expensive
    check_price .d.> check_dates
    check_dates .u.> wish : dates not in trip dates
    check_weather .u.> wish : don't fit
    check_weather .d.> check_price
    check_dates .d.> new_trip_element

}



@enduml
