@startuml
top to bottom direction

skinparam actorStyle awesome
actor User
actor Participants

"wish to organize a trip" as (wish)
"find place to travel" as (place)

:User: -r-|> wish
:User: ---|> book
wish .> place
place .r.> transfer

rectangle transfer {
    "find transfer" as (transfer_find)
    "check price" as (transfer_check_price)

    transfer_find ..> transfer_check_price
    transfer_check_price .r.> (accommodation)
    transfer_check_price ..> (place) : too expensive
}

rectangle accommodation {
    "find accommodation" as (accommodation_find)
    "check accommodation price" as (accommodation_check_price)

    accommodation_find ..> accommodation_check_price
    accommodation_check_price .r.> (weather)
    accommodation_check_price .d.> (place) : too expensive
}

rectangle weather {
    "check weather" as (weather_check)

    weather_check ..> (accept)
    weather_check ..> (place) : don't fit
}

rectangle accept {
   "accept trip" as (trip_accept)

   :Participants: --|> trip_accept
   trip_accept ..> book
}

rectangle book {
    "book transfer" as (book_transfer)
    "book accommodation" as (book_accommodation)

    book_transfer ..> book_accommodation
    book_accommodation .r.> "regional trip"
}

rectangle "regional trip" {
    "book additional trips in destination" as (book_additional_trips)
}



@enduml
