@startuml
top to bottom direction

skinparam actorStyle awesome
actor User

"wish to organize a trip" as (wish)
"find place to travel" as (place)

:User: -r-|> wish
wish .> place
place .r.> transfer

rectangle transfer {
    "find transfer" as (transfer_find)
    "check price" as (transfer_check_price)

    transfer_find ..> transfer_check_price
    transfer_check_price .r.> (accommodation)
    transfer_check_price ..> (place) : too expensive
}

rectangle accommodation {
    "find accommodation" as (accommodation_find)
    "check accommodation price" as (accommodation_check_price)

    accommodation_find ..> accommodation_check_price
    accommodation_check_price .r.> (weather)
    accommodation_check_price .d.> (place) : too expensive
}

rectangle weather {
    "check weather" as (weather_check)

    weather_check ..> (accept)
    weather_check ..> (place) : don't fit
}



@enduml
